train_dir   : 'data/train'
valid_dir   : 'data/valid'
dataset     : 'mu200_1pT'
log_dir     : 'logs/test/'
run_type    : 'new_run'
gpu         : '0'
n_files     : 4
n_valid     : 2
n_train     : 2
batch_size  : 1 
lr_c        : 0.01
n_iters     : 2
n_epoch     : 2
TEST_every  : 0
hid_dim     : 4
network     : 'QGNN'
optimizer: 'Adam'
loss_func: 'BinaryCrossentropy'
n_thread    : 8
log_verbosity: 2
EN_qc:
  PQC_id  : 'qc10_pqc_identity'
  IEC_id  : 'simple_encoding_y'
  MC_id   : 'measure_all'
  n_layers : 2
  repetitions: 0
  n_qubits: 4
NN_qc:
  PQC_id  : 'qc10_pqc_identity'
  IEC_id  : 'simple_encoding_y'
  MC_id   : 'measure_all'
  n_layers : 2
  repetitions: 0
  n_qubits: 4